trigger:
 - master
pool:
  vmImage: ubuntu-latest

stages:
  - stage: A
    jobs:
      - job: IISrecycleAppPool

- task: IISWebAppManagementOnMachineGroup@0
  inputs:
    IISDeploymentType: 'IISApplicationPool'
    ActionIISApplicationPool: 'RecycleAppPool'
    StartStopRecycleAppPoolName: 'IVR'
    
  
 
     

      


 
