
trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
 targetDirectory: 'C:\Users\Priya\Delete'
 filePattern: '*.*'

steps:
- checkout: self
- task: PowerShell@2
  inputs:
    targetType: 'filePath'
    filePath: '$(System.DefaultWorkingDirectory)/Deletefiles.ps1'
    arguments: '-targetDirectory $(targetDirectory) -filePattern $(filePattern)'
    pwsh: true


          

        
    

        




  


