trigger:
 - master
pool:
  vmImage: ubuntu-latest

stages:
  - stage: A
    displayName: "DEV"
    jobs:
      - job: DEV
  - stage: B
    displayName: "INTG"
    jobs:
      - job: INTG
        timeoutInMinutes: 5
        continueOnError: true
        cancelTimeoutInMinutes: 2
        

      


 
