
trigger:
- none

pool:
  vmImage: ubuntu-latest
 

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      Remove-Item "C:\Users\Priya\Delete*.*"


          

        
    

        




  


