
trigger:
- none

pool:
  vmImage: ubuntu-latest
  variables:
    - name: Toaddress
      value: pmahor4714@gmail.com 

stages:
  - stage: A
    jobs:
      - job: Sendemail
        
          

        
    

        




  


